const topic = {
  createCategory: 'category.createCategory',
  createCategoryFailed: 'category.createCategoryFailed',
  createCategorySuccess: 'category.createCategorySuccess',
  updateCategory: 'category.updateCategory',
  updateCategoryFailed: 'category.updateCategoryFailed',
  updateCategorySuccess: 'category.updateCategorySuccess',
  createProductLanguage: 'productLanguage.createProductLanguage',
  createProductLanguageFailed: 'productLanguage.createProductLanguageFailed',
  createProductLanguageSuccess: 'productLanguage.createProductLanguageSuccess',
  updateProductLanguage: 'productLanguage.updateProductLanguage',
  updateProductLanguageFailed: 'productLanguage.updateProductLanguageFailed',
  updateProductLanguageSuccess: 'productLanguage.updateProductLanguageSuccess',
  createProduct: 'product.createProduct',
  createProductFailed: 'product.createProductFailed',
  createProductSuccess: 'product.createProductSuccess',
  updateProduct: 'product.updateProduct',
  updateProductFailed: 'product.updateProductFailed',
  updateProductSuccess: 'product.updateProductSuccess',
}
export default topic
