const topic = {
  createCategory: 'category.createCategory',
  createCategoryFailed: 'category.createCategoryFailed',
  createCategorySuccess: 'category.createCategorySuccess',
  updateCategory: 'category.updateCategory',
  updateCategoryFailed: 'category.updateCategoryFailed',
  updateCategorySuccess: 'category.updateCategorySuccess',
  createProductLanguage: 'productLanguage.createProductLanguage',
  createProductLanguageFailed: 'productLanguage.createProductLanguageFailed',
  createProductLanguageSuccess: 'productLanguage.createProductLanguageSuccess',
  updateProductLanguage: 'productLanguage.updateProductLanguage',
  updateProductLanguageFailed: 'productLanguage.updateProductLanguageFailed',
  updateProductLanguageSuccess: 'productLanguage.updateProductLanguageSuccess',
  createProduct: 'product.createProduct',
  createProductFailed: 'product.createProductFailed',
  createProductSuccess: 'product.createProductSuccess',
  updateProduct: 'product.updateProduct',
  updateProductFailed: 'product.updateProductFailed',
  updateProductSuccess: 'product.updateProductSuccess',
  createProductPrice: 'productPrice.createProductPrice',
  createProductPriceFailed: 'productPrice.createProductPriceFailed',
  createProductPriceSuccess: 'productPrice.createProductPriceSuccess',
  updateProductPrice: 'productPrice.updateProductPrice',
  updateProductPriceFailed: 'productPrice.updateProductPriceFailed',
  updateProductPriceSuccess: 'productPrice.updateProductPriceSuccess',
  createProductPriceLanguage: 'productPriceLanguage.createProductPriceLanguage',
  createProductPriceLanguageFailed: 'productPriceLanguage.createProductPriceLanguageFailed',
  createProductPriceLanguageSuccess: 'productPriceLanguage.createProductPriceLanguageSuccess',
  updateProductPriceLanguage: 'productPriceLanguage.updateProductPriceLanguage',
  updateProductPriceLanguageFailed: 'productPriceLanguage.updateProductPriceLanguageFailed',
  updateProductPriceLanguageSuccess: 'productPriceLanguage.updateProductPriceLanguageSuccess',
}
export default topic
