POST http://localhost:9090/productLanguage HTTP/1.1

{
    "id": "rvJmNSSp1Xt",
    "attachment": [
        {
            "id": "dSZOv9EZJJr",
            "attachmentType": "image",
            "mimeType": "png",
            "url": "https://www.google.com",
            "validFor": {
                "endDateTime": "2023-10-25T23:59:59+07:00",
                "startDateTime": "2023-09-28T00:00:00+07:00"
            },
            "redirectUrl": "https://www.google.com",
            "displayInfo": {
                "valueType": "plaintext",
                "value": [
                    "แมวเหมียว"
                ]
            }
        }
    ],
    "languageCode": "th"
}

###
POST http://localhost:9090/productLanguage HTTP/1.1

{
    "id": "49rOwYkhq6U",
    "attachment": [
        {
            "id": "mMxErW9ljli",
            "attachmentType": "image",
            "mimeType": "png",
            "url": "https://www.google.com",
            "validFor": {
                "endDateTime": "2023-10-25T23:59:59+07:00",
                "startDateTime": "2023-09-28T00:00:00+07:00"
            },
            "redirectUrl": "https://www.google.com",
            "displayInfo": {
                "valueType": "plaintext",
                "value": [
                    "cat"
                ]
            }
        }
    ],
    "languageCode": "en"
}


###
GET http://localhost:9090/productLanguage HTTP/1.1