POST http://localhost:2566/category HTTP/1.1

{
  "id": "Zr9HD1erKpr",
  "name": "cpu",
  "version": "1.0",
  "lastUpdate": "2023-10-22",
  "lifecycleStatus": "active",
  "validFor": {
    "startDateTime": "2023-10-22T08:00:00Z",
    "endDateTime": "2029-10-23T08:00:00Z"
  }
}

###
POST http://localhost:2566/category HTTP/1.1

{
  "id": "LOw7TrRqMRX",
  "name": "gpu",
  "version": "1.0",
  "lastUpdate": "2023-10-22",
  "lifecycleStatus": "active",
  "validFor": {
    "startDateTime": "2023-10-22T08:00:00Z",
    "endDateTime": "2029-10-23T08:00:00Z"
  }
}

###
POST http://localhost:2566/category HTTP/1.1

{
  "id": "hdTrp4oXG7e",
  "name": "ram",
  "version": "1.0",
  "lastUpdate": "2023-10-22",
  "lifecycleStatus": "active",
  "validFor": {
    "startDateTime": "2023-10-22T08:00:00Z",
    "endDateTime": "2029-10-23T08:00:00Z"
  }
}

###
GET http://localhost:2566/category HTTP/1.1

###
GET http://localhost:2566/category?name=cpu,gpu,ram&lifecycleStatus=active HTTP/1.1