POST http://localhost:8080/category HTTP/1.1

{
  "id": "Zr9HD1erKpr",
  "name": "Category",
  "version": "1.0",
  "lastUpdate": "2023-10-22",
  "validFor": {
    "startDateTime": "2023-10-22T08:00:00Z",
    "endDateTime": "2029-10-23T08:00:00Z"
  }
}

###
GET http://localhost:8080/category HTTP/1.1